### ISSUE TITLE
Issue on graphs examples

### ISSUE THREAD

**Issue by alessandro-t** [Hanjun-Dai/graphnn#4] opened 2017-06-02 11:16 UTC
Hi. I tried to run the graph classification example but I experienced the following error:
```
Assertion isReady[VarIdx(p)] failed in src/nn/factor_graph.cpp line 173: required variable ReduceMean_21:out_0 is not ready
```
I'm trying to run the code on Ubuntu 16.04 and I read from another closed issue that it maybe could be the problem.

**Comment by Hanjun-Dai** [comment] 2017-06-02 20:51
Hi, yes I guess that's because of some discrepancy between operating systems. I'll try to figure it out under 16.04.

**Comment by apir8181** [comment] 2017-08-15 06:15
I encountered a similar error when run the mnist example:

<pre><code>
Assertion isReady[VarIdx(p)] failed in src/nn/factor_graph.cpp line 172: required variable ReduceMean_7:out_0 is not ready
</code></pre>

My runtime OS is Ubuntu 16.04. Please fix this problem.

**Comment by Hanjun-Dai** [comment] 2017-08-22 19:21
The issue is now fixed. Please pull the latest version. 

https://github.com/Hanjun-Dai/graphnn/commit/2f2500851fe7692fedeaf26ed815b0c4352d6a15

**Closed by Hanjun-Dai** 2017-08-22 19:21 UTC
